UNIVERSAL_LABEL_LIST = [
    "kettle", "microwave", "fridge", "freezer", "fridge_freezer", "dishwasher", "washing_machine",
    "tumble_dryer", "washer_dryer", "electric_heater", "toaster", "television", "desktop_computer",
    "laptop", "monitor", "router", "modem", "hi_fi", "games_console", "bread_maker", "food_mixer",
    "dehumidifier", "vivarium", "pond_pump", "space_heater", "air_conditioner", "blender", "slow_cooker",
    "water_heater", "refrigerated_drawer", "printer", "scanner", "smart_speaker", "smart_plug",
    "network_device", "projector", "charger", "coffee_machine", "iron", "hair_dryer", "lamp", "boiler",
    "oven", "fan", "radio", "amp", "vacuum_cleaner", "speakers", "htpc", "subwoofer", "set_top_box",
    "hair_straightener", "soldering_iron", "treadmill", "rice_cooker", "lighting_circuit",
    "baby_monitor", "aggregate", "other",
    "induction_cooktop", "heat_pump"
]


LABEL_KEYWORDS_MAP = {
    "aggregate": ["aggregate", "aggregate VA"],
    "amp": ["amp", "amp_livingroom", "Amplifier", "amplifier2", "amplifier4"],
    "baby_monitor": ["baby_monitor_tx", "baby monitor", "babymonitor"],
    "blender": ["blender"],
    "boiler": ["boiler", "gas_boiler"],
    "bread_maker": ["bread-maker", "bread maker", "breadmaker"],
    "charger": ["charger", "ipad_charger", "samsung_charger", "bedroom_chargers", "battery_charger", "Laptopcharger", "Charger82", "charger40"],
    "coffee_machine": ["coffee_machine", "nespresso_pixie", "coffeemaker"],
    "dehumidifier": ["dehumidifier"],
    "desktop_computer": ["desktop", "desktop computer", "computer site", "mjy computer", "pgm computer", "computer", "i7_desktop", "office_pc", "core2_server", "atom_pc", "data_logger_pc", "macmini"],
    "dishwasher": ["dishwasher", "dish_washer"],
    "electric_heater": ["electric heater", "heater", "electric_heater", "space_heater"],
    "evcharger": ["EVcharger"],
    "fan": ["office_fan", "Ventilation"],
    "food_mixer": ["food mixer", "k mix", "magimix", "kitchen_phone&stereo"],
    "freezer": ["freezer", "chest freezer"],
    "fridge": ["fridge"],
    "fridge_freezer": ["fridge-freezer", "fridge freezer", "fridgefreezer", "fridge_freezer"],
    "games_console": ["games console", "game console", "xbox", "playstation", "ps4", "PS4"],
    "hair_dryer": ["hairdryer", "hair_dryer"],
    "hair_straightener": ["straighteners", "hair_straightener"],
    "heat_pump": ["Heat_pump"],
    "hi_fi": ["hi-fi", "hi fi", "hifi", "hifi_office", "home_theatre_amp"],
    "htpc": ["htpc", "mediaplayer"],
    "induction_cooktop": ["Induction_cooktop"],
    "iron": ["iron", "steam_iron"],
    "kettle": ["kettle"],
    "lamp": [
        "lamp", "livingroom_s_lamp", "livingroom_s_lamp2", "kitchen_dt_lamp", "bedroom_ds_lamp",
        "bedroom_d_lamp", "office_lamp1", "office_lamp2", "office_lamp3", "childs_table_lamp", "childs_ds_lamp",
        "utilityrm_lamp", "kitchen_lamp2", "lightbulb81", "lightbulb41"
    ],
    "laptop": ["laptop", "macbook", "laptop2"],
    "lighting_circuit": ["lighting_circuit", "Outdoor_lightning"],
    "microwave": ["microwave"],
    "modem": ["modem"],
    "monitor": ["monitor", "lcd_office", "24_inch_lcd", "24_inch_lcd_bedroom", "monitor14", "monitor2"],
    "network_device": ["network site", "computer site", "server", "server_hdd", "nas", "network_attached_storage", "gigE_&_USBhub"],
    "other": ["kitchenappliances"],
    "oven": ["oven", "gas_oven", "Oven1", "Oven2"],
    "printer": ["printer", "LED_printer"],
    "projector": ["projector"],
    "radio": ["dab_radio", "kitchen_radio", "tv_dvd_digibox_lamp", "kettle_radio"],
    "refrigerated_drawer": ["refrigerated drawer"],
    "rice_cooker": ["rice_cooker"],
    "router": ["router", "network site", "adsl_router"],
    "scanner": ["scanner"],
    "set_top_box": ["sky_hd_box", "set top box"],
    "slow_cooker": ["slow cooker"],
    "smart_plug": ["smart plug"],
    "smart_speaker": ["smart speaker", "musicstreamer", "musicstreamer6"],
    "soldering_iron": ["soldering_iron"],
    "speakers": ["speakers", "stereo_speakers_bedroom"],
    "subwoofer": ["subwoofer", "subwoofer_livingroom"],
    "television": ["television", "tv site", "tv", "primary_tv", "tv_dvd_digibox_lamp", "livingroom_lamp_tv", "TV2", "TV3", "TV4"],
    "toaster": ["toaster"],
    "treadmill": ["running_machine", "treadmill"],
    "tumble_dryer": ["tumble dryer", "laundry_dryer"],
    "vacuum_cleaner": ["vacuum_cleaner", "hoover", "robotvacum", "vacumcleaner"],
    "washer_dryer": ["washer dryer", "washer/dryer", "washer_dryer"],
    "washing_machine": ["washing machine", "washing_machine"],
    "water_heater": ["water heater"]
}
